### ISSUE TITLE
Enemy Health Bars

### ISSUE THREAD

**Issue by JuiceGrape** [JuiceGrape/Incarnation-Of-Ragnarok#10]
When enemies are attacked, they should show a health bar floating above their head indicating how much HP they have left.

TODO:

- [ ] Create HP bar prefab
- [ ] Add HP bar prefab to enemies and all enemy prefabs that currently exist
- [ ] Make sure the prefab is linked to the HP resource of enemies
