### ISSUE TITLE
Make player attackable

### ISSUE THREAD

**Issue by JuiceGrape** [JuiceGrape/Incarnation-Of-Ragnarok#11]
The player needs to be attackable for enemies.

TODO:

- [ ] Add HP to the player
- [ ] Represent the HP on the UI using some shitty HP bar you find online (or a good one)
- [ ] The player cannot be a hittable, otherwise the player would be to attack themselves, this needs to be a different but very similar public interface

Out of scope:
- Death State
- Other resources and UI parts
