### ISSUE TITLE
Add preloading to level transitions

### ISSUE THREAD

**Issue by JuiceGrape** [JuiceGrape/Incarnation-Of-Ragnarok#13]
Blocked by #4 
When travelling to a new room, they are fully loaded (without a loading bar) when clicked. Instead, we want the new scenes to be pre-loaded when they are generated. The cpu load on this should be minimal to the point that the player does not notice. When a target room is picked, the player is moved into the new scene instantly (if the room has been loaded already, if not, just make the player wait for now). The other pre-loaded room(s) should be unloaded automatically.

TODO:

- [ ] Make rooms load in asynchronously during gameplay so they are done loading by the time the exits open
- [ ] Unload unused scenes after moving to the new one
- [ ] If not possible: research and suggest possible alternatives to this.
