### ISSUE TITLE
Move attacking mechanics out of player controller and into a separate abstractable class

### ISSUE THREAD

**Issue by JuiceGrape** [JuiceGrape/Incarnation-Of-Ragnarok#2]
The mechanics for dealing damage or attacking enemies is currently contained in the player controller. Because most enemies will use the same animation controller as the player does, it is a good idea to move this code out of the player controller and into a separate class. It is also a good idea to create an interface that provides the necessary components for attacking (I.E. damage, damage type, projectile, etc.).

TODO:

- [x] Add interface to Player class which provides everything needed for attacking so monsters can implement this separately
- [x] Make attacking code dependant on new interface
- [x] Move attacking code (AttackTriggered) into separate component so it can be re-used
