### ISSUE TITLE
Enemy spawning

### ISSUE THREAD

**Issue by JuiceGrape** [JuiceGrape/Incarnation-Of-Ragnarok#3]
Whenever a player enters a room (hits a trigger collider), the monsters in that room should start spawning. This spawning will happen in waves. Waves happen sequentially, and only when certain triggers are met. Each wave is a single Scriptable Object containing a trigger and a list of enemies to spawn at which locations. 

The spawner script should have a list of spawn locations that the wave references by index number. The spawner script will take a list of enemies to spawn and an amount of them to spawn, and will spawn them in a spread around itself a set number of seconds after it has received the command.

Supported triggers:

- [ ] Instant
- [ ] Time Based
- [ ] Percentage of wave kill based
- [ ] Specific monster of wave kill based

TODO:

- [ ] Create spawner script which can take a list of enemies and number of each to spawn around itself
- [ ] Create wave scriptable object that has a trigger and a list of enemies paired with a number of enemies and a target spawner index
- [ ] Create a wave logic script that confirms a trigger and moves on to the next wave if that trigger is complete.
- [ ] Create an event within the wave logic script that is called when the final wave has spawned and all spawned enemies of all waves have been defeated
- [ ] Add functionality to enemies to report their death with certain parameters, for now: SpawnerIndex, WaveIndex, Enemy ID
