### ISSUE TITLE
Chain rooms

### ISSUE THREAD

**Issue by JuiceGrape** [JuiceGrape/Incarnation-Of-Ragnarok#4]
Whenever a player clears a room, they must be able to go to a new room when interacting with the exits of the current room. This next room should be randomly picked from a list of available rooms. Every room has a scriptable object attached to it, which provides at least 2 possible rooms to go to. This scriptable object should also contain at least 1 boss room to go to.. If the nth(5) room in a row is reached, one of the exits should lead to the boss room. This gives the player a choice in what room they go to, and also a choice to skip the boss (for now).

TODO:

- [ ] Create script that teleports the player to a new room when an exit is pressed.
- [ ] Create a scriptable object that holds a pool of rooms with weights and a pool of boss rooms (no weights).
- [ ] Create a script that counts the number of rooms that have passed. This persists between rooms. This script also contains the variable which allows us to choose the amount of rooms that happen before we encounter a boss.
- [ ] At the start of a scene, randomly choose 2 rooms from the pool, and if it is the nth room in a row, make one of those a random boss.
- [ ] Make the random choosing algorithm include weights which scale linearly (I.E. a room of weight 3 is thrice as likely to occur than a room of weight 1).
- [ ] Make sure the algorithm doesn't pick 2 duplicates. If only 1 room is in the list, only allow 1 of the exists to be used.

Notes
- Each room is its own unity scene.
- Rooms can lead to other types (I.E. forest -> town). 
- For now these unlock at the start. If #3 is finished before this, attach the room cleared event to the unlocking of the rooms.
- You can make an object interactable by adding a script that inherits from interactable to it and activating it. As long as it isn't active, the player cannot interact with it.
- Make sure the entire player gets put in the new map

Out of scope:
- Pre-loading target rooms or using loading bars, just a simple LoadScene will work just fine for now
- Making rooms
- Spawning the player when the dungeon starts. Assume it already exists when entering.
