### ISSUE TITLE
Enemy AI

### ISSUE THREAD

**Issue by JuiceGrape** [JuiceGrape/Incarnation-Of-Ragnarok#5]
Make a start with enemy AI: Walk towards the player and use basic attacks on them. Also make them die when their HP gets too low. Use a state machine

TODO:

- [ ] Make spawned enemies target the player
- [ ] Make scriptable object for basic enemy attacks
- [ ] Make spawned enemies attack the player when close enough
- [ ] Add death state to enemies, making them disappear n seconds after the death animation ends (maybe ragdoll after death instead for max funny)
- [ ] Make sure enemies are no longer targetable when dead, and that the player controller realizes this

**Comment by JuiceGrape** [comment]
Could re-use weapons instead of making scriptable objects for basic enemy attacks from the player to have more shared code instead
