### ISSUE TITLE
Create inventory system basics

### ISSUE THREAD

**Issue by JuiceGrape** [JuiceGrape/Incarnation-Of-Ragnarok#7]
Create a system where the player can have items in their inventory.

TODO:

- [x] Create inventory that can hold items
- [x] Each item is a piece of gear
- [ ] Each item has a rarity and a level, which can algorithmically be used as modifiers for any damage
- [x] Add icons to the Weapon
- [x] Replace the Weapon in the Player with an Item of type weapon that has a rarity and uses this in the damage calculation.
- [ ] Create a temporary UI that can be brought up and closed by pressing I (add to input system).
- [x] Make the UI show any items that are in the inventory
- [x] Make sure the inventory has a function that can be used to add an item to the inventory

Out of scope:
- Updating UI when item gets added while it is open (unless its easy / free)
- Picking up items
