### ISSUE TITLE
Item pickups

### ISSUE THREAD

**Issue by JuiceGrape** [JuiceGrape/Incarnation-Of-Ragnarok#9]
Create objects that can lay on the floor  which are picked up when interacted with. They will also show a name above the object when it is hovered over and on the ground.

TODO:

- [ ] Create script that takes an item object and becomes that item, after which it can be interacted with to be picked up
- [ ] Make sure that the object's model turns into the item's model
- [ ] Make the item name hover above the item when it is on the floor and hovered over
- [ ] Colour the item name according to the rarity: Broken = grey, Fixed = white, Improved = green, Unique = Red

Out of scope:
- Random generation of items
